### ISSUE TITLE
Question: How to import a OpenOffice Dictionary ?

### ISSUE THREAD

**Issue by robgha01** [sheitmann/AgentSmith#10]
Where do i import the Open Office language files ?

The instructions i found misses the option specefied in https://code.google.com/archive/p/agentsmithplugin/wikis/FAQ.wiki

as its an archived version i guess it may not even be up to date.

**Comment by sheitmann** [comment]
Hi,
it is out of date yes.

First you have to convert the Open Office dictionary to a NetSpell dictionary.
NetSpell is what Agent Smith is using for spell checking. You can find more about it here:
http://www.codeproject.com/Articles/5277/NetSpell-Spell-Checker-for-NET

To convert it run the tool named NetSpell.DictionaryBuild, contained in this zip file, look into the bin folder:
https://sourceforge.net/projects/netspell/files/NetSpell/NetSpell%202.1.7/NetSpell.2.1.7.zip/download

In this tool you have to create a new dictionary and with Dictionary -> Add Open Office Word List / Add Open Office Affix data you can add the Open Office dictionary data to this NetSpell dictionary.

Last but not least save the new dic file in the folder %AppData%\Agent Smith\dic
If you want resx checking to work your dictionary name must match a valid CultureInfo.
In the ReSharper Options below Tools you find AgenSmith. Add the file name without .dic to the list of spell check dictionary names. You have one on each setting (Identifier, Inline Comments, Resources, Strings, Xml Documentation -> General).

Hope this helps.

I will update the wiki on github to include this information.
There is a chance that this function is added to the addin in some simple way or that I switch to NHunspell at some point because it provides me less false spell check errors with German word compared to NetSpell.

Br
Sven

**Comment by robgha01** [comment]
@sheitmann Thanks i followed your instructions and the spell checking is now working, it would be nice if this process was easier and NHunspell would be awesome but as a first step its good with a updated wiki thanks for a lovely extension would not live without it xD :+1:

**Comment by sheitmann** [comment]
There is some piece of code in the class OpenOfficeDictionaryImporter for importing, but it is not available for the user at the moment. I will bring it back.

**Comment by robgha01** [comment]
ok :) yea i scumed the source code before i read the old wiki and found that interesting code piece but could not find any usages which explains way.

**Comment by robgha01** [comment]
by the way, i downloaded a open office dictionary file which crashed the program you linked so some dictionaries may be corrupted or something.

**Comment by sheitmann** [comment]
I created #11 for the import

**Comment by sheitmann** [comment]
make sure you use an Open Office 2 dictionary
I can check what needs to be done to support Open Office 3 or 4 dictionaries.

**Comment by sheitmann** [comment]
@robgha01 
can you link the dictionary where you got the exception? could be interesting to see the reason.

**Comment by robgha01** [comment]
@sheitmann I deleted the file... and can't seem to undelete nor find it at open office dictionaries source, i suspect that the file was downloaded from some other source or that the en dictionary file at open office may not exist. the error i had if i try to remember the type was someting like null reference exception.. tried to find the log in windows log manager found nothing with the application. xD
